title: Ruzies' Feed
author: Ruzie
subtitle: Everything you may ever ask yourself/someone else

url: "https://github.com/Ruzie"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: ""
profile-picture: assets/profile.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: sass

navbar:
 - name: "About"
   link: "about"
 - name: "GitHub"
   absolute-link: "https://github.com/Ruzie"
