title: Kiwimoes' Feed
author: kiwimoe
subtitle: Everything you may ever ask yourself/someone else

url: "https://github.com/Ruzie"
profile-picture: assets/profile.png

permalink: /:year-:month-:day-:title/
navbar:
 - name: "About"
   link: "about"
 - name: "GitHub"
   absolute-link: "https://github.com/kiwimoe"
